<?php
// All niche landing-page content. Add a niche = add an entry here + a /<slug>/index.php stub.
return [

  'koffiebar' => [
    'name' => 'Koffiebar',
    'title' => 'Digitale klantenkaart voor koffiebars | Stampzer',
    'desc' => 'Dé digitale spaarkaart voor je koffiebar of café. Klanten sparen voor een gratis koffie, direct in Apple & Google Wallet — nooit meer kwijt. Meer terugkerende klanten. Schrijf je in.',
    'keywords' => 'digitale klantenkaart koffiebar, stempelkaart café, spaarkaart koffie, koffie spaarkaart app, loyaliteitsprogramma koffiebar, gratis koffie sparen',
    'eyebrow' => 'Voor koffiebars & cafés',
    'h1a' => 'Digitale klantenkaart voor koffiebars die klanten ', 'mark' => 'terug laat komen', 'h1b' => '.',
    'sub' => 'Geef je koffiebar een eigen digitale spaarkaart in Apple Wallet en Google Wallet. Klanten sparen bij elk kopje voor een gratis koffie — en raken hun kaart nooit meer kwijt. Meer vaste klanten, ook op rustige momenten.',
    'pass' => ['theme' => 'coffee', 'icon' => 'coffee', 'biz' => 'Koffiehoek', 'sub' => 'Koffiebar · Utrecht', 'reward' => '10ᵉ koffie gratis', 'on' => 7, 'total' => 10, 'progress' => 'Nog 3 kopjes tot je gratis koffie'],
    'trustLabel' => 'Gemaakt voor elke koffiezaak',
    'trust' => ['Koffiebars', 'Cafés', 'Espressobars', 'Koffie to-go', 'Lunchcafés'],
    'place' => 'koffiebar', 'visit' => 'kopje koffie',
    'pains' => [
      ['Klanten halen koffie waar het uitkomt', 'Zonder reden om terug te komen pakken ze hun cappuccino net zo makkelijk bij de zaak om de hoek.'],
      ['Papieren stempelkaartjes raken zoek', 'Verkreukeld in een tas of allang weg. Een kaart die je klant kwijt is, levert niks op.'],
      ['Je weet niet wie je vaste klanten zijn', 'Je kent de gezichten, maar mist namen, cijfers en overzicht van wie er dagelijks komt.'],
      ['Rustige uren blijven rustig', 'Tussen de spitsen door staat het stil, zonder manier om klanten juist dan binnen te trekken.'],
    ],
    'rewards' => [
      ['coffee', '10ᵉ koffie gratis', 'De klassieker — spaar 9, de 10e is van de zaak.'],
      ['percent', 'Tweede koffie halve prijs', 'Beloon wie vaker langskomt met korting.'],
      ['gift', 'Gratis gebakje na 6 stempels', 'Koppel koffie aan iets lekkers erbij.'],
      ['star', 'Gratis to-go beker', 'Een hebbeding voor je trouwste klanten.'],
    ],
    'statNum' => '€5.000',
    'statLine' => '300 vaste klanten die door hun spaarkaart 1× per week extra langskomen, bij €4 per koffie.',
    'statSub' => 'Dat is een rekenvoorbeeld van zo\'n €5.000 extra omzet per maand — alleen van klanten die anders misschien niet waren teruggekomen. Ruwe inschatting; jouw cijfers bepalen het.',
    'faq' => [
      ['Werkt een digitale klantenkaart voor mijn koffiebar?', 'Ja. Of je nu een espressobar, café of koffie-to-go hebt — je stelt je eigen spaarkaart en beloning in. Klanten sparen bij elk kopje en komen vaker terug.'],
      ['Hebben mijn klanten een app nodig?', 'Nee. De kaart komt in de Apple Wallet of Google Wallet die al op elke telefoon staat. Eén QR-code scannen en klaar.'],
      ['Wat voor beloning kan ik instellen?', 'Alles wat past: een gratis koffie na een aantal stempels, korting, een gratis gebakje of een to-go beker. Jij bepaalt het.'],
      ['Werkt het op iPhone én Android?', 'Ja, zowel Apple Wallet als Google Wallet worden ondersteund.'],
    ],
    'hubTagline' => 'Spaar voor een gratis koffie', 'hubIcon' => 'coffee',
  ],

  'nagelstudio' => [
    'name' => 'Nagelstudio',
    'title' => 'Digitale klantenkaart voor nagelstudio\'s | Stampzer',
    'desc' => 'Dé digitale spaarkaart voor je nagelstudio. Klanten sparen bij elke behandeling voor een beloning, direct in Apple & Google Wallet. Meer terugkerende klanten, voller geboekt. Schrijf je in.',
    'keywords' => 'digitale klantenkaart nagelstudio, spaarkaart nagelstudio, stempelkaart nagels, loyaliteitsprogramma nagelsalon, klantenkaart beauty, klantenbinding nagelstudio',
    'eyebrow' => 'Voor nagelstudio\'s & beautysalons',
    'h1a' => 'Digitale klantenkaart voor nagelstudio\'s waar klanten ', 'mark' => 'blijven terugkomen', 'h1b' => '.',
    'sub' => 'Geef je nagelstudio een eigen digitale spaarkaart in Apple Wallet en Google Wallet. Klanten sparen bij elke behandeling voor een beloning — en raken hun kaart nooit meer kwijt. Een voller geboekte agenda met vaste klanten.',
    'pass' => ['theme' => 'nails', 'icon' => 'flower', 'biz' => 'Studio Bloom', 'sub' => 'Nagelstudio · Rotterdam', 'reward' => 'Gratis behandeling', 'on' => 5, 'total' => 8, 'progress' => 'Nog 3 behandelingen tot je beloning'],
    'trustLabel' => 'Gemaakt voor elke nagel- & beautysalon',
    'trust' => ['Nagelstudio\'s', 'Beautysalons', 'Wimperstylisten', 'Schoonheidssalons', 'Pedicures'],
    'place' => 'salon', 'visit' => 'behandeling',
    'pains' => [
      ['Klanten boeken niet meteen opnieuw', 'Na een behandeling is de volgende afspraak zo vergeten — en gaan ze de volgende keer ergens anders heen.'],
      ['Papieren kaartjes verdwijnen in tassen', 'Een verkreukeld stempelkaartje motiveert niemand om terug te komen.'],
      ['Geen zicht op je trouwe klanten', 'Je weet niet wie er regelmatig komt, wie bijna een beloning heeft of wie al een tijd wegblijft.'],
      ['Gaten in je agenda', 'Op rustige dagen blijft de stoel leeg, zonder manier om klanten een zetje te geven.'],
    ],
    'rewards' => [
      ['flower', 'Gratis behandeling', 'Spaar een vol kaartje en de volgende is gratis.'],
      ['percent', '15% korting na 5 bezoeken', 'Beloon trouwe klanten met een vaste korting.'],
      ['gift', 'Gratis nagellak of cadeautje', 'Geef een product weg en verkoop er meteen meer.'],
      ['star', 'Gratis nagelreparatie', 'Een fijne extra voor je vaste klanten.'],
    ],
    'statNum' => '€3.200',
    'statLine' => '150 vaste klanten die door hun spaarkaart 1× per maand extra boeken, bij ongeveer €40 per behandeling.',
    'statSub' => 'Een rekenvoorbeeld van zo\'n €3.200 extra omzet per maand — alleen van klanten die anders misschien niet hadden geboekt. Ruwe inschatting; jouw cijfers bepalen het.',
    'faq' => [
      ['Werkt een digitale klantenkaart voor mijn nagelstudio?', 'Ja. Of je nu nagels, wimpers of huidverzorging doet — je stelt je eigen spaarkaart en beloning in. Klanten sparen per behandeling en komen vaker terug.'],
      ['Hebben mijn klanten een app nodig?', 'Nee. De kaart komt in de Apple Wallet of Google Wallet die al op elke telefoon staat. Eén QR-code scannen en klaar.'],
      ['Wat voor beloning kan ik instellen?', 'Alles wat past: een gratis behandeling, korting, een gratis product of een reparatie. Jij bepaalt het en past het elk moment aan.'],
      ['Werkt het op iPhone én Android?', 'Ja, zowel Apple Wallet als Google Wallet worden ondersteund.'],
    ],
    'hubTagline' => 'Spaar voor een gratis behandeling', 'hubIcon' => 'flower',
  ],

  'lunchroom' => [
    'name' => 'Lunchroom',
    'title' => 'Digitale klantenkaart voor lunchrooms | Stampzer',
    'desc' => 'Dé digitale spaarkaart voor je lunchroom. Klanten sparen bij elke lunch voor een beloning, direct in Apple & Google Wallet — nooit meer kwijt. Meer vaste gasten. Schrijf je in.',
    'keywords' => 'digitale klantenkaart lunchroom, spaarkaart lunchroom, stempelkaart lunch, loyaliteitsprogramma horeca, klantenkaart broodjeszaak, klantenbinding lunchroom',
    'eyebrow' => 'Voor lunchrooms & broodjeszaken',
    'h1a' => 'Digitale klantenkaart voor lunchrooms waar gasten ', 'mark' => 'vaker terugkomen', 'h1b' => '.',
    'sub' => 'Geef je lunchroom een eigen digitale spaarkaart in Apple Wallet en Google Wallet. Gasten sparen bij elke lunch voor een beloning — en raken hun kaart nooit meer kwijt. Meer vaste gasten op je drukste én rustige dagen.',
    'pass' => ['theme' => 'lunch', 'icon' => 'cutlery', 'biz' => 'Lunchroom Vers', 'sub' => 'Lunchroom · Den Haag', 'reward' => '8ᵉ lunch gratis', 'on' => 5, 'total' => 8, 'progress' => 'Nog 3 lunches tot je gratis lunch'],
    'trustLabel' => 'Gemaakt voor elke lunchzaak',
    'trust' => ['Lunchrooms', 'Broodjeszaken', 'Salade-bars', 'Bakkerijcafés', 'To-go lunch'],
    'place' => 'lunchroom', 'visit' => 'lunch',
    'pains' => [
      ['Veel passanten, weinig vaste gasten', 'Mensen lunchen waar het toevallig uitkomt. Zonder reden om terug te komen blijft het bij één bezoek.'],
      ['Papieren stempelkaartjes raken kwijt', 'Tussen de bonnetjes verdwenen of weggegooid — en daarmee de motivatie om terug te komen.'],
      ['Geen idee wie je vaste gasten zijn', 'Je herkent gezichten, maar hebt geen namen, cijfers of overzicht.'],
      ['Stille dagen blijven stil', 'Buiten de lunchpiek staat het rustig, zonder manier om gasten een zetje te geven.'],
    ],
    'rewards' => [
      ['cutlery', '8ᵉ lunch gratis', 'Spaar 7 lunches, de 8e is van de zaak.'],
      ['coffee', 'Gratis koffie bij je lunch', 'Een kleine plus die gasten terugbrengt.'],
      ['percent', '10% korting na 5 bezoeken', 'Beloon vaste gasten met korting.'],
      ['gift', 'Gratis verse smoothie', 'Iets lekkers extra voor je trouwste gasten.'],
    ],
    'statNum' => '€4.300',
    'statLine' => '250 vaste gasten die door hun spaarkaart 1× per maand extra langskomen, bij ongeveer €11 per lunch.',
    'statSub' => 'Een rekenvoorbeeld van zo\'n €4.300 extra omzet per maand — puur van gasten die anders misschien niet waren teruggekomen. Ruwe inschatting; jouw cijfers bepalen het.',
    'faq' => [
      ['Werkt een digitale klantenkaart voor mijn lunchroom?', 'Ja. Of je nu een lunchroom, broodjeszaak of saladebar hebt — je stelt je eigen spaarkaart en beloning in. Gasten sparen per lunch en komen vaker terug.'],
      ['Hebben mijn gasten een app nodig?', 'Nee. De kaart komt in de Apple Wallet of Google Wallet die al op elke telefoon staat. Eén QR-code scannen en klaar.'],
      ['Wat voor beloning kan ik instellen?', 'Alles wat past: een gratis lunch, gratis koffie erbij, korting of een verse smoothie. Jij bepaalt het.'],
      ['Werkt het op iPhone én Android?', 'Ja, zowel Apple Wallet als Google Wallet worden ondersteund.'],
    ],
    'hubTagline' => 'Spaar voor een gratis lunch', 'hubIcon' => 'cutlery',
  ],

  'sportschool' => [
    'name' => 'Sportschool',
    'title' => 'Digitale klantenkaart voor sportscholen | Stampzer',
    'desc' => 'Dé digitale spaarkaart voor je sportschool of gym. Leden sparen voor beloningen en blijven gemotiveerd, direct in Apple & Google Wallet. Meer betrokken leden, minder opzeggingen. Schrijf je in.',
    'keywords' => 'digitale klantenkaart sportschool, spaarkaart gym, loyaliteitsprogramma sportschool, ledenbinding sportschool, klantenkaart fitness, stempelkaart sportschool',
    'eyebrow' => 'Voor sportscholen, gyms & studio\'s',
    'h1a' => 'Digitale klantenkaart voor sportscholen die leden ', 'mark' => 'gemotiveerd houdt', 'h1b' => '.',
    'sub' => 'Geef je sportschool een eigen digitale spaarkaart in Apple Wallet en Google Wallet. Leden sparen bij elke training voor een beloning — een extra reden om te blijven komen. Meer betrokken leden en minder opzeggingen.',
    'pass' => ['theme' => 'gym', 'icon' => 'dumbbell', 'biz' => 'Gym Forta', 'sub' => 'Sportschool · Eindhoven', 'reward' => 'Gratis maand na 30 trainingen', 'on' => 6, 'total' => 10, 'progress' => 'Nog 4 trainingen tot je beloning'],
    'trustLabel' => 'Gemaakt voor elke sportlocatie',
    'trust' => ['Sportscholen', 'Gyms', 'Yogastudio\'s', 'CrossFit-boxen', 'Personal trainers'],
    'place' => 'sportschool', 'visit' => 'training',
    'pains' => [
      ['Leden haken na een paar weken af', 'Zonder zichtbaar doel verslapt de motivatie — en een afhaker is vaak een opzegging.'],
      ['Geen beloning voor wie trouw komt', 'Je fanatieke leden krijgen niets extra\'s, terwijl juist zij je beste ambassadeurs zijn.'],
      ['Weinig zicht op betrokkenheid', 'Je weet niet wie er vaak traint, wie afglijdt of wie bijna een mijlpaal haalt.'],
      ['Mond-tot-mondreclame blijft liggen', 'Tevreden leden brengen geen vrienden mee, omdat er geen prikkel voor is.'],
    ],
    'rewards' => [
      ['dumbbell', 'Gratis maand na 30 trainingen', 'Beloon trouw trainen met een gratis periode.'],
      ['gift', 'Gratis shaker of handdoek', 'Een hebbeding bij een volle kaart.'],
      ['percent', 'Korting op PT-sessie', 'Zet sparen om in een upsell.'],
      ['star', 'Gratis proefweek voor een vriend', 'Maak van leden je beste werving.'],
    ],
    'statNum' => '€3.600',
    'statLine' => '200 leden die dankzij hun spaarkaart langer lid blijven, bij €30 contributie per maand en 3 maanden extra retentie.',
    'statSub' => 'Een rekenvoorbeeld van zo\'n €3.600 extra omzet per maand aan behouden contributie — leden die anders misschien hadden opgezegd. Ruwe inschatting; jouw cijfers bepalen het.',
    'faq' => [
      ['Werkt een digitale klantenkaart voor mijn sportschool?', 'Ja. Of je nu een gym, yogastudio of CrossFit-box hebt — je stelt je eigen spaarkaart en beloning in. Leden sparen per training en blijven gemotiveerd.'],
      ['Hebben mijn leden een app nodig?', 'Nee. De kaart komt in de Apple Wallet of Google Wallet die al op elke telefoon staat. Eén QR-code scannen en klaar.'],
      ['Wat voor beloning kan ik instellen?', 'Alles wat past: een gratis maand, een shaker of handdoek, korting op personal training of een proefweek voor een vriend. Jij bepaalt het.'],
      ['Werkt het op iPhone én Android?', 'Ja, zowel Apple Wallet als Google Wallet worden ondersteund.'],
    ],
    'hubTagline' => 'Spaar voor beloningen & blijf gemotiveerd', 'hubIcon' => 'dumbbell',
  ],

  'bakker' => [
    'name' => 'Bakker',
    'title' => 'Digitale klantenkaart voor bakkers | Stampzer',
    'desc' => 'Dé digitale spaarkaart voor je bakkerij. Klanten sparen bij elke aankoop voor een gratis brood of gebakje, direct in Apple & Google Wallet — nooit meer kwijt. Meer vaste klanten. Schrijf je in.',
    'keywords' => 'digitale klantenkaart bakker, spaarkaart bakkerij, stempelkaart bakker, loyaliteitsprogramma bakkerij, klantenkaart bakkerij, klantenbinding bakker',
    'eyebrow' => 'Voor bakkers & bakkerijen',
    'h1a' => 'Digitale klantenkaart voor bakkers waar klanten ', 'mark' => 'blijven terugkomen', 'h1b' => '.',
    'sub' => 'Geef je bakkerij een eigen digitale spaarkaart in Apple Wallet en Google Wallet. Klanten sparen bij elke aankoop voor een gratis brood of gebakje — en raken hun kaart nooit meer kwijt. Meer vaste klanten, elke ochtend opnieuw.',
    'pass' => ['theme' => 'bakker', 'icon' => 'bread', 'biz' => 'Bakkerij Vers', 'sub' => 'Bakker · Haarlem', 'reward' => '10ᵉ brood gratis', 'on' => 6, 'total' => 10, 'progress' => 'Nog 4 broden tot je gratis brood'],
    'trustLabel' => 'Gemaakt voor elke bakkerij',
    'trust' => ['Ambachtelijke bakkers', 'Warme bakkers', 'Banketbakkers', 'Broodjeszaken', 'Bakkerijcafés'],
    'place' => 'bakkerij', 'visit' => 'aankoop',
    'pains' => [
      ['Klanten kopen brood waar het uitkomt', 'Zonder reden om terug te komen halen ze hun brood net zo makkelijk bij de supermarkt of de bakker verderop.'],
      ['Papieren stempelkaartjes raken kwijt', 'Verkreukeld tussen de bonnetjes of allang weg — en daarmee de reden om terug te komen.'],
      ['Je weet niet wie je vaste klanten zijn', 'Je kent de ochtendgezichten, maar mist namen, cijfers en overzicht van wie er dagelijks komt.'],
      ['Rustige middagen blijven rustig', 'Na de ochtendspits blijft er brood liggen, zonder manier om klanten juist dan binnen te trekken.'],
    ],
    'rewards' => [
      ['bread', '10ᵉ brood gratis', 'De klassieker — spaar 9, het 10e is van de zaak.'],
      ['gift', 'Gratis gebakje na 6 stempels', 'Koppel je brood aan iets lekkers erbij.'],
      ['percent', '10% korting op je verjaardag', 'Een fijne attentie die klanten bindt.'],
      ['star', 'Vers stokbrood in het weekend', 'Een extraatje voor je trouwste klanten.'],
    ],
    'statNum' => '€4.800',
    'statLine' => '300 vaste klanten die door hun spaarkaart 1× per week extra langskomen, bij ongeveer €4 per aankoop.',
    'statSub' => 'Een rekenvoorbeeld van zo\'n €4.800 extra omzet per maand — alleen van klanten die anders misschien niet waren teruggekomen. Ruwe inschatting; jouw cijfers bepalen het.',
    'faq' => [
      ['Werkt een digitale klantenkaart voor mijn bakkerij?', 'Ja. Of je nu een ambachtelijke bakker, warme bakker of banketbakker bent — je stelt je eigen spaarkaart en beloning in. Klanten sparen bij elke aankoop en komen vaker terug.'],
      ['Hebben mijn klanten een app nodig?', 'Nee. De kaart komt in de Apple Wallet of Google Wallet die al op elke telefoon staat. Eén QR-code scannen en klaar.'],
      ['Wat voor beloning kan ik instellen?', 'Alles wat past: een gratis brood na een aantal stempels, een gratis gebakje, korting of vers stokbrood in het weekend. Jij bepaalt het.'],
      ['Werkt het op iPhone én Android?', 'Ja, zowel Apple Wallet als Google Wallet worden ondersteund.'],
    ],
    'hubTagline' => 'Spaar voor een gratis brood', 'hubIcon' => 'bread',
  ],

  // Kapper is a standalone static page (/kapper/index.html); listed here only for the hub.
  'kapper' => [
    'name' => 'Kapper', 'hubOnly' => true,
    'hubTagline' => 'Spaar voor een gratis knipbeurt', 'hubIcon' => 'scissors',
  ],

];
